# Based on Node 8.x LTS image
FROM node:8.11.2

# Set the default directory where CMD will execute
WORKDIR /app

# Copy some utility files
COPY ./eline/.babelrc .
COPY ./eline/.eslintrc .
COPY ./eline/.eslintignore .

# Install node requirements
COPY ./eline/package.json .
COPY ./eline/package-lock.json ./

# Install node dependencies
RUN npm install

# Set the default command to execute when creating a new container
CMD npm run build
