# Based on Node 8.x LTS image
FROM node:9.8.0

# Set the default directory where CMD will execute
WORKDIR /app

# Set the default command to execute when creating a new container
CMD /bin/bash -c "npm install && npm run dev"
